<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password</name>
   <tag></tag>
   <elementGuidId>a847b2a0-eb6d-4fd2-8284-79a383c22266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2476c6ec-23d4-4179-8f2b-a35648e5aa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>5c380e51-03ac-4cf3-94c8-56723c9a4552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d3a9b94b-820e-424c-9c23-2f1a518067cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d42e1a7f-1235-44c1-af47-b07e007bc63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine igx-input-group__input ng-invalid</value>
      <webElementGuid>64fedd4c-49fa-4805-8a4e-d980261a658a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-input-group-1&quot;)/div[@class=&quot;igx-input-group__bundle&quot;]/div[@class=&quot;igx-input-group__bundle-main&quot;]/input[@class=&quot;ng-untouched ng-pristine igx-input-group__input ng-invalid&quot;]</value>
      <webElementGuid>c0b4cf7b-9ca9-45e8-8d4d-49fbd847cfee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Password']</value>
      <webElementGuid>207012b1-7a8c-4e15-b715-b2980838377e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-1']/div/div/input</value>
      <webElementGuid>f989ed0d-7c2f-4260-b08d-29eeb833ca4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/igx-input-group/div/div/input</value>
      <webElementGuid>4059b373-4cfb-4568-868a-c3f05e02b0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Password' and @type = 'password']</value>
      <webElementGuid>65dd4375-a395-4164-9fd8-4c9e037f494e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
